spring:
  datasource:
    url: "jdbc:mysql://10.8.0.1:3306/spring"
    username: "flow"
    password: "Password.1"
    platform: "mysql"
    initialization-mode: never
  jpa:
    show-sql: true
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    hibernate:
      ddl-auto: create

